# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 23:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AimController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.BooleanField(default=False)),
                ('control', models.IntegerField(default=0)),
                ('sellsafe', models.IntegerField(default=10)),
                ('buysafe', models.IntegerField(default=10)),
                ('buymin', models.IntegerField(default=500)),
                ('sellmin', models.IntegerField(default=500)),
                ('buyperc', models.IntegerField(default=10)),
                ('sellperc', models.IntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HoldingAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('buyprice', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sellprice', models.DecimalField(decimal_places=3, max_digits=10)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.Holding')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('permission', models.CharField(choices=[('X', 'None - Owner only'), ('V', 'Public View')], default='X', max_length=10)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('high', models.DecimalField(decimal_places=3, max_digits=12)),
                ('low', models.DecimalField(decimal_places=3, max_digits=12)),
                ('close', models.DecimalField(decimal_places=3, max_digits=12)),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('currentprice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pricelink', to='aim.Price')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shares', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('type', models.CharField(choices=[('Buy', 'Buy Shares'), ('Sell', 'Sell Shares')], default='Buy', max_length=10)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.Holding')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.Symbol'),
        ),
        migrations.AddField(
            model_name='holding',
            name='currentalert',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alertholding', to='aim.HoldingAlert'),
        ),
        migrations.AddField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.Portfolio'),
        ),
        migrations.AddField(
            model_name='holding',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.Symbol'),
        ),
        migrations.AddField(
            model_name='aimcontroller',
            name='holding',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controller', to='aim.Holding'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together=set([('name', 'owner')]),
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set([('portfolio', 'symbol')]),
        ),
    ]
