# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('emailed', models.BooleanField(default=False)),
                ('alert', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aim.HoldingAlert')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.Holding')),
            ],
        ),
    ]
