apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: loadprices
spec:
  schedule: "0 * * * *"  
  jobTemplate:
    spec:
      template:
        metadata:
          lables:
            parent: "loadprices"
        spec:
          restartPolicy: Never
          containers:
          - name: loadprices
            image: 172.30.118.67:5000/stocksonthebeach/django
            env:
              - name: APP_SCRIPT
                value: "loadprices.sh"
              - name: FTPPASS
                value: "Got1eoddata"
              - name: FTPLOGIN
                value: "jfmatth"
              - name: EMAIL_USER
                value: "registration@compunique.com"
              - name: EMAIL_PASSWORD
                value: "Pa55word"
              - name: DEBUG
                value: "True"