apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: loadprices
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: loadprices
            image: 172.30.1.1:5000/myproject/aim:latest
            args:
          restartPolicy: Never