apiVersion: batch/v1
kind: Job
metadata:
  name: loadprices
spec:
  template:
    metadata:
      name: loadprices
    spec:
      containers:
      - name: loadprices
        image: 172.30.118.67:5000/aimit/django
        env:
          - name: APP_SCRIPT
            value: "loadprices.sh"
      restartPolicy: Never
      backoffLimit: 1